### PR TITLE
Refactor JS code of streaming

### PR DESCRIPTION
**Pull request by corneadoug**
There is no need to use DOM and JQuery here, angular data binding takes care of it

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @corneadoug. The reason i manipulate DOM was, i wasn't sure about the performance of 'refreshing' angular data binding, especially output becomes thousand of lines.
What do you think? Will angular data binding has no performance implication appending line after line?

**Comment by corneadoug** [comment]
The size of the data wouldn't matter. For the refresh, We are already having similar behavior with progress bar.

In Angular, what counts for performance is: Nb of watchers (values with data binding, here its only one), and the time of the digest loop (time to go through all the watchers). In this case we are good. On the other hand, accessing DOM is know to be an expensive task.

This is a good read: https://www.airpair.com/angularjs/posts/angularjs-performance-large-applications

**Comment by Leemoonsoo** [comment]
Okay i got that. Then, will there be any performance implication in web browser? since updating data binding make browser re-render that area.

**Comment by corneadoug** [comment]
I think it should be fine, there would be higher priority elsewhere to improve performances. Thats something we will have to work on while refactoring in the future.

**Comment by Leemoonsoo** [comment]
@corneadoug 
Test this code.

```
(1 to 3000).foreach{i => 
    (1 to 80).foreach(i=>print(i))
    println("")
}
```

without DOM manipulate, it struggles printing large number of lines.

**Comment by corneadoug** [comment]
Its slightly better, especially on scroll. However in both you can't do anything else and the page pretty much freeze

**Comment by Leemoonsoo** [comment]
On my machine with/without dom manipulatuon have some meaningfull differences. One not freeze the browser but the other freeze.

**Comment by corneadoug** [comment]
Okay, then thats fine for now

**Pull request closed without merging**
